fragment AppForPinnedList on App {
  id
  name
  slug
  latestActivity
  icon {
    url
    primaryColor
  }
  ownerAccount {
    name
  }
}

query GetAppsForPinnedList {
  viewer {
    accounts {
      id
      appsPaginated(first: 10, filter: { sortByField: LATEST_ACTIVITY_TIME }) {
        edges {
          cursor
          node {
            ...AppForPinnedList
          }
        }
      }
    }
  }
}
