fragment CurrentUserData on UserActor {
  id
  username
  firstName
  lastName
  bestContactEmail
  primaryAccountProfileImageUrl
}

query GetCurrentUser {
  meUserActor {
    ...CurrentUserData
  }
}
