import { InternalError } from 'common-types';
import { PairAndroidDeviceResult } from 'common-types/build/cli-commands/pairAndroidDevice';
import { Emulator } from 'eas-shared';

type PairAndroidDeviceOptions = {
  pairingAddress: string;
  pairingCode: string;
  /**
   * The `ipAddress:port` used to connect to the device. On Android this differs
   * from the pairing address. When omitted, only the pairing step is performed.
   */
  connectAddress?: string;
};

export async function pairAndroidDeviceAsync({
  pairingAddress,
  pairingCode,
  connectAddress,
}: PairAndroidDeviceOptions): Promise<PairAndroidDeviceResult> {
  try {
    await Emulator.pairAndroidDeviceAsync({ pairingAddress, pairingCode });

    if (connectAddress) {
      await Emulator.connectAndroidDeviceAsync(connectAddress);
    }

    return { success: true };
  } catch (error) {
    return getResultFromError(error);
  }
}

type PairAndroidDeviceWithQRCodeOptions = {
  serviceName: string;
  pairingCode: string;
  timeout?: string;
};

const DEFAULT_SCAN_TIMEOUT_MS = 3 * 60 * 1000;
const CONNECT_DISCOVERY_TIMEOUT_MS = 15 * 1000;

/**
 * Pair a device that scanned a QR code generated by the menu bar app. Once
 * scanned, the device advertises an mDNS pairing service named `serviceName`,
 * which we discover through `adb mdns services` to obtain its address.
 */
export async function pairAndroidDeviceWithQRCodeAsync({
  serviceName,
  pairingCode,
  timeout,
}: PairAndroidDeviceWithQRCodeOptions): Promise<PairAndroidDeviceResult> {
  try {
    const timeoutMs = timeout ? parseInt(timeout, 10) : DEFAULT_SCAN_TIMEOUT_MS;

    console.log('Waiting for the device to scan the QR code...');
    const pairingService = await Emulator.waitForAdbMdnsServiceAsync({
      serviceType: 'pairing',
      serviceName,
      timeoutMs,
    });
    if (!pairingService) {
      return {
        success: false,
        error: {
          code: 'QR_SCAN_TIMEOUT',
          message: 'Timed out waiting for the device to scan the QR code.',
        },
      };
    }

    console.log(`Pairing with ${pairingService.address}...`);
    await Emulator.pairAndroidDeviceAsync({
      pairingAddress: pairingService.address,
      pairingCode,
    });

    // After pairing, the device advertises a connect service on the same IP
    // (with a different port). Connecting makes it show up in `adb devices`.
    console.log('Connecting to the device...');
    const connectService = await Emulator.waitForAdbMdnsServiceAsync({
      serviceType: 'connect',
      ipAddress: pairingService.address.split(':')[0],
      timeoutMs: CONNECT_DISCOVERY_TIMEOUT_MS,
    });
    if (connectService) {
      await Emulator.connectAndroidDeviceAsync(connectService.address);
    }

    return { success: true };
  } catch (error) {
    return getResultFromError(error);
  }
}

function getResultFromError(error: unknown): PairAndroidDeviceResult {
  if (error instanceof Error) {
    return {
      success: false,
      error: {
        code: error instanceof InternalError ? error.code : 'UNKNOWN_ERROR',
        message: error.message,
      },
    };
  }

  throw error;
}
