import { InternalError } from 'common-types';
import { PairAndroidDeviceResult } from 'common-types/build/cli-commands/pairAndroidDevice';
import { Emulator } from 'eas-shared';

type PairAndroidDeviceOptions = {
  pairingAddress: string;
  pairingCode: string;
  /**
   * The `ipAddress:port` used to connect to the device. On Android this differs
   * from the pairing address. When omitted, only the pairing step is performed.
   */
  connectAddress?: string;
};

const CONNECT_DISCOVERY_TIMEOUT_MS = 15 * 1000;

/**
 * Logged the instant pairing succeeds, before the (slow) connect-discovery
 * step. The menu bar app watches for this to show "paired" right away while the
 * connect finishes in the background.
 */
const DEVICE_PAIRED_LOG = '[orbit] device paired';

export async function pairAndroidDeviceAsync({
  pairingAddress,
  pairingCode,
  connectAddress,
}: PairAndroidDeviceOptions): Promise<PairAndroidDeviceResult> {
  try {
    await Emulator.pairAndroidDeviceAsync({ pairingAddress, pairingCode });
    console.log(DEVICE_PAIRED_LOG);
    await connectAfterPairingAsync({ pairingAddress, connectAddress });

    return { success: true };
  } catch (error) {
    return getResultFromError(error);
  }
}

/**
 * Connect to a device right after pairing. When the caller already knows the
 * connect address we use it directly; otherwise we discover the connect service
 * over mDNS (it lives on the same IP as the pairing service, different port),
 * matching what Android Studio does so the user never types an address.
 */
async function connectAfterPairingAsync({
  pairingAddress,
  connectAddress,
}: {
  pairingAddress: string;
  connectAddress?: string;
}): Promise<void> {
  if (connectAddress) {
    await Emulator.connectAndroidDeviceAsync(connectAddress);
    return;
  }

  console.log('Connecting to the device...');
  const connectService = await Emulator.waitForAdbMdnsServiceAsync({
    serviceType: 'connect',
    ipAddress: pairingAddress.split(':')[0],
    timeoutMs: CONNECT_DISCOVERY_TIMEOUT_MS,
  });
  if (connectService) {
    await Emulator.connectAndroidDeviceAsync(connectService.address);
  }
}

type PairAndroidDeviceWithQRCodeOptions = {
  serviceName: string;
  pairingCode: string;
  timeout?: string;
};

const DEFAULT_SCAN_TIMEOUT_MS = 3 * 60 * 1000;

/**
 * Pair a device that scanned a QR code generated by the menu bar app. Once
 * scanned, the device advertises an mDNS pairing service named `serviceName`,
 * which we discover through `adb mdns services` to obtain its address.
 */
export async function pairAndroidDeviceWithQRCodeAsync({
  serviceName,
  pairingCode,
  timeout,
}: PairAndroidDeviceWithQRCodeOptions): Promise<PairAndroidDeviceResult> {
  try {
    const timeoutMs = timeout ? parseInt(timeout, 10) : DEFAULT_SCAN_TIMEOUT_MS;

    console.log('Waiting for the device to scan the QR code...');
    const pairingService = await Emulator.waitForAdbMdnsServiceAsync({
      serviceType: 'pairing',
      serviceName,
      timeoutMs,
    });
    if (!pairingService) {
      return {
        success: false,
        error: {
          code: 'QR_SCAN_TIMEOUT',
          message: 'Timed out waiting for the device to scan the QR code.',
        },
      };
    }

    console.log(`Pairing with ${pairingService.address}...`);
    await Emulator.pairAndroidDeviceAsync({
      pairingAddress: pairingService.address,
      pairingCode,
    });
    console.log(DEVICE_PAIRED_LOG);
    await connectAfterPairingAsync({ pairingAddress: pairingService.address });

    return { success: true };
  } catch (error) {
    return getResultFromError(error);
  }
}

/**
 * List Android devices currently advertising a Wi-Fi pairing service over mDNS
 * (i.e. sitting on the "Pair device with pairing code" screen). Mirrors the
 * device list Android Studio shows so the user just picks one and types the code.
 */
export async function listAndroidPairingServicesAsync(): Promise<AdbPairingService[]> {
  const services = await Emulator.getAdbMdnsServicesAsync();
  return services
    .filter((service) => service.serviceType.startsWith('_adb-tls-pairing'))
    .map((service) => ({ name: service.name, address: service.address }));
}

type AdbPairingService = { name: string; address: string };

function getResultFromError(error: unknown): PairAndroidDeviceResult {
  if (error instanceof Error) {
    return {
      success: false,
      error: {
        code: error instanceof InternalError ? error.code : 'UNKNOWN_ERROR',
        message: error.message,
      },
    };
  }

  throw error;
}
