import { InternalError } from 'common-types';
import { PairAndroidDeviceResult } from 'common-types/build/cli-commands/pairAndroidDevice';
import { Emulator } from 'eas-shared';

type PairAndroidDeviceOptions = {
  /** `code` pairs with a manually-entered address, `qr` waits for a scan. */
  mode: 'code' | 'qr';
  /** `code` mode: the code typed by the user. Generated by the CLI in `qr` mode. */
  pairingCode?: string;
  /** `code` mode: the `ipAddress:port` shown on the pairing dialog. */
  pairingAddress?: string;
  /**
   * `code` mode: the `ipAddress:port` used to connect to the device. On Android
   * this differs from the pairing address. When omitted it is discovered over mDNS.
   */
  connectAddress?: string;
  /** `qr` mode: how long to wait for the device to scan, in milliseconds. */
  timeout?: string;
};

const CONNECT_DISCOVERY_TIMEOUT_MS = 15 * 1000;

/**
 * Logged the instant pairing succeeds, before the (slow) connect-discovery
 * step. The menu bar app watches for this to show "paired" right away while the
 * connect finishes in the background.
 */
const DEVICE_PAIRED_LOG = '[orbit] device paired';

/**
 * Prefix for the line that carries the QR payload to render. The menu bar app
 * watches for this so the CLI owns generating the pairing secret.
 */
const QR_CODE_LOG_PREFIX = '[orbit] qr-code ';

function randomAlphanumeric(length: number): string {
  const chars = 'ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789';
  return Array.from({ length }, () => chars[Math.floor(Math.random() * chars.length)]).join('');
}

export async function pairAndroidDeviceAsync(
  options: PairAndroidDeviceOptions
): Promise<PairAndroidDeviceResult> {
  if (options.mode === 'qr') {
    return pairWithQRCodeAsync(options);
  }
  return pairWithPairingCodeAsync(options);
}

async function pairWithPairingCodeAsync({
  pairingAddress,
  pairingCode,
  connectAddress,
}: PairAndroidDeviceOptions): Promise<PairAndroidDeviceResult> {
  if (!pairingAddress || !pairingCode) {
    return {
      success: false,
      error: {
        code: 'INVALID_ARGS',
        message: '--pairing-address and --pairing-code are required in "code" mode.',
      },
    };
  }

  try {
    await Emulator.pairAndroidDeviceAsync({ pairingAddress, pairingCode });
    console.log(DEVICE_PAIRED_LOG);
    await connectAfterPairingAsync({ pairingAddress, connectAddress });

    return { success: true };
  } catch (error) {
    return getResultFromError(error);
  }
}

/**
 * Connect to a device right after pairing. When the caller already knows the
 * connect address we use it directly; otherwise we discover the connect service
 * over mDNS (it lives on the same IP as the pairing service, different port),
 * matching what Android Studio does so the user never types an address.
 */
async function connectAfterPairingAsync({
  pairingAddress,
  connectAddress,
}: {
  pairingAddress: string;
  connectAddress?: string;
}): Promise<void> {
  if (connectAddress) {
    await Emulator.connectAndroidDeviceAsync(connectAddress);
    return;
  }

  console.log('Connecting to the device...');
  const connectService = await Emulator.waitForAdbMdnsServiceAsync({
    serviceType: 'connect',
    ipAddress: pairingAddress.split(':')[0],
    timeoutMs: CONNECT_DISCOVERY_TIMEOUT_MS,
  });
  if (connectService) {
    await Emulator.connectAndroidDeviceAsync(connectService.address);
  }
}

const DEFAULT_SCAN_TIMEOUT_MS = 3 * 60 * 1000;

/**
 * Generate a pairing QR code, emit it for the menu bar app to render, then wait
 * for the device to scan it. Once scanned, the device advertises an mDNS pairing
 * service named `serviceName`, which we discover to obtain its address.
 */
async function pairWithQRCodeAsync({
  timeout,
}: PairAndroidDeviceOptions): Promise<PairAndroidDeviceResult> {
  // The pairing secret is minted here so the menu bar app never handles it.
  const serviceName = `expo-orbit-${randomAlphanumeric(10)}`;
  const pairingCode = randomAlphanumeric(8);
  console.log(`${QR_CODE_LOG_PREFIX}WIFI:T:ADB;S:${serviceName};P:${pairingCode};;`);

  try {
    const timeoutMs = timeout ? parseInt(timeout, 10) : DEFAULT_SCAN_TIMEOUT_MS;

    console.log('Waiting for the device to scan the QR code...');
    const pairingService = await Emulator.waitForAdbMdnsServiceAsync({
      serviceType: 'pairing',
      serviceName,
      timeoutMs,
    });
    if (!pairingService) {
      return {
        success: false,
        error: {
          code: 'QR_SCAN_TIMEOUT',
          message: 'Timed out waiting for the device to scan the QR code.',
        },
      };
    }

    console.log(`Pairing with ${pairingService.address}...`);
    await Emulator.pairAndroidDeviceAsync({
      pairingAddress: pairingService.address,
      pairingCode,
    });
    console.log(DEVICE_PAIRED_LOG);
    await connectAfterPairingAsync({ pairingAddress: pairingService.address });

    return { success: true };
  } catch (error) {
    return getResultFromError(error);
  }
}

/**
 * List Android devices currently advertising a Wi-Fi pairing service over mDNS
 * (i.e. sitting on the "Pair device with pairing code" screen). Mirrors the
 * device list Android Studio shows so the user just picks one and types the code.
 */
export async function listAndroidPairingServicesAsync(): Promise<AdbPairingService[]> {
  const services = await Emulator.getAdbMdnsServicesAsync();
  return services
    .filter((service) => service.serviceType.startsWith('_adb-tls-pairing'))
    .map((service) => ({ name: service.name, address: service.address }));
}

type AdbPairingService = { name: string; address: string };

function getResultFromError(error: unknown): PairAndroidDeviceResult {
  if (error instanceof Error) {
    return {
      success: false,
      error: {
        code: error instanceof InternalError ? error.code : 'UNKNOWN_ERROR',
        message: error.message,
      },
    };
  }

  throw error;
}
