import { execFile } from 'child_process';
import { CliCommands, InternalError, StorageUtils } from 'common-types';
import { promises as fs } from 'fs';
import os from 'os';
import path from 'path';

type ShellCommandStatus = CliCommands.ShellCommand.ShellCommandStatus;

const COMMAND_NAME = 'orbit';

// Set by the Electron main process for the CLI it forks (see electron/src/main.ts). A terminal
// invocation doesn't go through the app, so the launcher has to carry them itself.
const FORWARDED_ENV_VARS = ['ORBIT_HELPER_BIN_DIR', 'ORBIT_ANISETTE_ASSETS_DIR'];

/** How to start this same CLI again from a terminal. */
export type Launcher = {
  command: string[];
  env: Record<string, string>;
};

export type ExecFn = (
  file: string,
  args: string[],
  env?: Record<string, string>
) => Promise<string>;

export type ShellCommandContext = {
  platform: NodeJS.Platform;
  homedir: string;
  launcher: Launcher;
  exec: ExecFn;
  /** PATH entries the user's shells start with, used to tell whether `linkPath` is reachable. */
  pathEntries: () => Promise<string[]>;
  /** Directory for the `orbit` symlink on macOS/Linux. Defaults per platform, see `getPaths`. */
  linkDir?: string;
};

export function getCurrentLauncher(): Launcher {
  const env: Record<string, string> = {};
  for (const key of FORWARDED_ENV_VARS) {
    const value = process.env[key];
    if (value) {
      env[key] = value;
    }
  }

  // macOS ships the CLI as a standalone `pkg` executable inside the app bundle.
  if ((process as any).pkg) {
    return { command: [process.execPath], env };
  }

  // Windows/Linux run the CLI bundle with the app's own Electron binary, the same way the app's
  // `fork()` does. ELECTRON_RUN_AS_NODE makes it behave as plain Node instead of opening the app.
  if (process.versions.electron) {
    env.ELECTRON_RUN_AS_NODE = '1';
  }
  return { command: [process.execPath, path.resolve(process.argv[1])], env };
}

function execAsync(file: string, args: string[], env?: Record<string, string>) {
  return new Promise<string>((resolve, reject) => {
    execFile(file, args, { env: { ...process.env, ...env } }, (error, stdout, stderr) => {
      if (error) {
        reject(new Error(stderr.trim() || error.message));
      } else {
        resolve(stdout);
      }
    });
  });
}

function getDefaultContext(): ShellCommandContext {
  const platform = process.platform;
  const exec = execAsync;
  return {
    platform,
    homedir: os.homedir(),
    launcher: getCurrentLauncher(),
    exec,
    pathEntries: async () => {
      if (platform === 'win32') {
        return (await exec('powershell.exe', POWERSHELL_ARGS, windowsPathEnv('list', '')))
          .split(/\r?\n/)
          .filter(Boolean);
      }
      if (platform === 'darwin') {
        // Apps launched from Finder get a minimal PATH, so read what login shells get instead.
        const etcPaths = await fs.readFile('/etc/paths', 'utf8').catch(() => '');
        return etcPaths.split('\n').map((entry) => entry.trim());
      }
      return (process.env.PATH ?? '').split(':');
    },
  };
}

function getPaths({ platform, homedir, linkDir: customLinkDir }: ShellCommandContext) {
  const p = platform === 'win32' ? path.win32 : path.posix;
  const shimDir = p.join(p.normalize(StorageUtils.getExpoOrbitDirectory(homedir)), 'bin');
  if (platform === 'win32') {
    return { shimDir, shimPath: p.join(shimDir, `${COMMAND_NAME}.cmd`), linkPath: shimDir };
  }
  // /usr/local/bin is on every macOS shell's PATH via /etc/paths. Linux distros put
  // ~/.local/bin on PATH instead, and writing there doesn't need root.
  const linkDir =
    customLinkDir ?? (platform === 'darwin' ? '/usr/local/bin' : p.join(homedir, '.local', 'bin'));
  return {
    shimDir,
    shimPath: p.join(shimDir, COMMAND_NAME),
    linkPath: p.join(linkDir, COMMAND_NAME),
  };
}

// Shims

const SHIM_HEADER = 'Generated by Expo Orbit. Orbit rewrites this file when it launches.';

function shQuote(value: string) {
  return `'${value.replace(/'/g, `'\\''`)}'`;
}

export function createPosixShim({ command, env }: Launcher) {
  return [
    '#!/bin/sh',
    `# ${SHIM_HEADER}`,
    `if [ ! -e ${shQuote(command[0])} ]; then`,
    `  echo ${shQuote(`orbit: Expo Orbit is no longer at ${command[0]}. Open Expo Orbit once to repair this command, or reinstall it.`)} >&2`,
    '  exit 127',
    'fi',
    ...Object.entries(env).map(([key, value]) => `export ${key}=${shQuote(value)}`),
    `exec ${command.map(shQuote).join(' ')} "$@"`,
    '',
  ].join('\n');
}

export function createWindowsShim({ command, env }: Launcher) {
  // Windows paths can't contain `"`, so quoting is enough; only `%` needs escaping in batch files.
  const escape = (value: string) => value.replace(/%/g, '%%');
  return [
    '@echo off',
    `rem ${SHIM_HEADER}`,
    'setlocal',
    `if not exist "${escape(command[0])}" goto missing`,
    ...Object.entries(env).map(([key, value]) => `set "${key}=${escape(value)}"`),
    `${command.map((part) => `"${escape(part)}"`).join(' ')} %*`,
    'exit /b %ERRORLEVEL%',
    ':missing',
    `echo orbit: Expo Orbit is no longer at "${escape(command[0])}". Open Expo Orbit once to repair this command, or reinstall it. 1>&2`,
    'exit /b 9009',
    '',
  ].join('\r\n');
}

async function writeShimAsync(context: ShellCommandContext) {
  const { shimDir, shimPath } = getPaths(context);
  const contents =
    context.platform === 'win32'
      ? createWindowsShim(context.launcher)
      : createPosixShim(context.launcher);
  await fs.mkdir(shimDir, { recursive: true });
  await fs.writeFile(shimPath, contents, { mode: 0o755 });
  // `mode` only applies when the file is created; make sure an existing shim stays executable.
  await fs.chmod(shimPath, 0o755);
}

// Windows user PATH

// Reads and writes the raw registry value so `%VAR%` entries stay unexpanded, and broadcasts
// WM_SETTINGCHANGE (via SetEnvironmentVariable) so terminals opened afterwards see the change.
const WINDOWS_PATH_SCRIPT = `
$dir = $env:ORBIT_SHELL_COMMAND_DIR
$key = [Microsoft.Win32.Registry]::CurrentUser.CreateSubKey('Environment')
$current = $key.GetValue('Path', '', [Microsoft.Win32.RegistryValueOptions]::DoNotExpandEnvironmentNames)
$entries = @($current -split ';' | Where-Object { $_ -ne '' })
$next = $null
switch ($env:ORBIT_SHELL_COMMAND_MODE) {
  'list' { $entries | ForEach-Object { [Environment]::ExpandEnvironmentVariables($_) }; break }
  'add' { if ($entries -notcontains $dir) { $next = @($entries) + $dir } ; break }
  'remove' { if ($entries -contains $dir) { $next = @($entries | Where-Object { $_ -ne $dir }) } ; break }
}
if ($null -ne $next) {
  $key.SetValue('Path', ($next -join ';'), [Microsoft.Win32.RegistryValueKind]::ExpandString)
  [Environment]::SetEnvironmentVariable('ORBIT_SHELL_COMMAND_SYNC', '1', 'User')
  [Environment]::SetEnvironmentVariable('ORBIT_SHELL_COMMAND_SYNC', $null, 'User')
}
$key.Close()
`;
const POWERSHELL_ARGS = [
  '-NoProfile',
  '-NonInteractive',
  '-ExecutionPolicy',
  'Bypass',
  '-Command',
  WINDOWS_PATH_SCRIPT,
];

function windowsPathEnv(mode: 'list' | 'add' | 'remove', dir: string) {
  return { ORBIT_SHELL_COMMAND_MODE: mode, ORBIT_SHELL_COMMAND_DIR: dir };
}

// POSIX symlink

async function readLinkAsync(linkPath: string) {
  try {
    const stat = await fs.lstat(linkPath);
    if (!stat.isSymbolicLink()) {
      return { exists: true, target: undefined };
    }
    return { exists: true, target: await fs.readlink(linkPath) };
  } catch (error: any) {
    if (error.code === 'ENOENT') {
      return { exists: false, target: undefined };
    }
    throw error;
  }
}

/**
 * Runs a filesystem change, retrying it with an administrator prompt on macOS when the target
 * directory isn't writable by the user (/usr/local/bin is root-owned unless Homebrew claimed it).
 */
async function withAdminFallbackAsync(
  context: ShellCommandContext,
  run: () => Promise<void>,
  { dir, shellCommand, prompt }: { dir: string; shellCommand: string; prompt: string }
) {
  try {
    await run();
  } catch (error: any) {
    if (context.platform !== 'darwin' || (error.code !== 'EACCES' && error.code !== 'EPERM')) {
      throw error;
    }
    try {
      // Pass the command through argv so it never has to be escaped as an AppleScript string.
      await context.exec('/usr/bin/osascript', [
        '-e',
        'on run argv',
        '-e',
        'do shell script (item 1 of argv) with prompt (item 2 of argv) with administrator privileges',
        '-e',
        'end run',
        shellCommand,
        prompt,
      ]);
    } catch (adminError: any) {
      throw new InternalError(
        'SHELL_COMMAND_PERMISSION_DENIED',
        `Administrator permission is required to change ${dir} (${adminError.message}).`
      );
    }
  }
}

// Commands

export async function getShellCommandStatusAsync(
  context: ShellCommandContext = getDefaultContext()
): Promise<ShellCommandStatus> {
  const { shimPath, linkPath } = getPaths(context);
  const shimExists = await fs
    .access(shimPath)
    .then(() => true)
    .catch(() => false);
  const pathEntries = await context.pathEntries();
  const p = context.platform === 'win32' ? path.win32 : path.posix;
  const linkDir = context.platform === 'win32' ? linkPath : p.dirname(linkPath);
  const onPath = pathEntries.some((entry) =>
    context.platform === 'win32'
      ? p.normalize(entry).toLowerCase() === linkDir.toLowerCase()
      : p.normalize(entry).replace(/\/$/, '') === linkDir
  );

  if (context.platform === 'win32') {
    return { installed: shimExists && onPath, shimPath, linkPath, onPath };
  }

  const link = await readLinkAsync(linkPath);
  const isOurs =
    link.target !== undefined && p.resolve(p.dirname(linkPath), link.target) === shimPath;
  return {
    installed: shimExists && isOurs,
    shimPath,
    linkPath,
    onPath,
    ...(link.exists && !isOurs
      ? { conflict: `${linkPath} already exists and wasn't installed by Expo Orbit.` }
      : {}),
  };
}

export async function installShellCommandAsync(
  options: { refresh?: boolean } = {},
  context: ShellCommandContext = getDefaultContext()
): Promise<ShellCommandStatus> {
  const { shimPath, linkPath } = getPaths(context);

  // On launch, the app only re-points an existing shim at itself, so moving Orbit.app or a
  // Squirrel update (which installs into a new versioned folder) doesn't break the command.
  if (options.refresh) {
    const shimExists = await fs
      .access(shimPath)
      .then(() => true)
      .catch(() => false);
    if (shimExists) {
      await writeShimAsync(context);
    }
    return getShellCommandStatusAsync(context);
  }

  const status = await getShellCommandStatusAsync(context);
  if (status.conflict) {
    throw new InternalError('SHELL_COMMAND_CONFLICT', status.conflict);
  }

  await writeShimAsync(context);

  if (context.platform === 'win32') {
    await context.exec('powershell.exe', POWERSHELL_ARGS, windowsPathEnv('add', linkPath));
  } else if (!(await readLinkAsync(linkPath)).exists) {
    // Any existing link is ours at this point, since conflicts were rejected above.
    const linkDir = path.posix.dirname(linkPath);
    await withAdminFallbackAsync(
      context,
      async () => {
        await fs.mkdir(linkDir, { recursive: true });
        await fs.symlink(shimPath, linkPath);
      },
      {
        dir: linkDir,
        shellCommand: `mkdir -p ${shQuote(linkDir)} && ln -s ${shQuote(shimPath)} ${shQuote(linkPath)}`,
        prompt: `Expo Orbit wants to install the "${COMMAND_NAME}" command in ${linkDir}.`,
      }
    );
  }

  return getShellCommandStatusAsync(context);
}

export async function uninstallShellCommandAsync(
  context: ShellCommandContext = getDefaultContext()
): Promise<ShellCommandStatus> {
  const { shimPath, linkPath } = getPaths(context);

  if (context.platform === 'win32') {
    await context.exec('powershell.exe', POWERSHELL_ARGS, windowsPathEnv('remove', linkPath));
  } else {
    const status = await getShellCommandStatusAsync(context);
    // Only ever remove our own symlink; a conflicting `orbit` belongs to someone else.
    if (!status.conflict && (await readLinkAsync(linkPath)).exists) {
      await withAdminFallbackAsync(context, () => fs.unlink(linkPath), {
        dir: path.posix.dirname(linkPath),
        shellCommand: `rm -f ${shQuote(linkPath)}`,
        prompt: `Expo Orbit wants to remove the "${COMMAND_NAME}" command from ${path.posix.dirname(linkPath)}.`,
      });
    }
  }

  await fs.rm(shimPath, { force: true });
  return getShellCommandStatusAsync(context);
}
