import { PairAndroidDeviceResult } from 'common-types/build/cli-commands/pairAndroidDevice';

import MenuBarModule from '../modules/MenuBarModule';

type PairAndroidDeviceAsyncOptions = {
  pairingAddress: string;
  pairingCode: string;
  connectAddress?: string;
};

export const pairAndroidDeviceAsync = async ({
  pairingAddress,
  pairingCode,
  connectAddress,
}: PairAndroidDeviceAsyncOptions) => {
  const args = ['--pairing-address', pairingAddress, '--pairing-code', pairingCode];
  if (connectAddress) {
    args.push('--connect-address', connectAddress);
  }

  const stringResult = await MenuBarModule.runCli('pair-android-device', args, undefined);

  return JSON.parse(stringResult) as PairAndroidDeviceResult;
};

type PairAndroidDeviceWithQRCodeAsyncOptions = {
  serviceName: string;
  pairingCode: string;
};

/**
 * Waits for a device to scan the QR code generated by the app and then pairs
 * with it. Resolves once the device is paired (or the CLI times out waiting).
 */
export const pairAndroidDeviceWithQRCodeAsync = async (
  { serviceName, pairingCode }: PairAndroidDeviceWithQRCodeAsyncOptions,
  onStatusUpdate?: (status: string) => void
) => {
  const args = ['--service-name', serviceName, '--pairing-code', pairingCode];

  const stringResult = await MenuBarModule.runCli('pair-android-device-qr', args, onStatusUpdate);

  return JSON.parse(stringResult) as PairAndroidDeviceResult;
};
