import { PairAndroidDeviceResult } from 'common-types/build/cli-commands/pairAndroidDevice';

import MenuBarModule from '../modules/MenuBarModule';

type PairAndroidDeviceAsyncOptions = {
  pairingAddress: string;
  pairingCode: string;
  connectAddress?: string;
};

export const pairAndroidDeviceAsync = async (
  { pairingAddress, pairingCode, connectAddress }: PairAndroidDeviceAsyncOptions,
  onStatusUpdate?: (status: string) => void
) => {
  const args = ['--pairing-address', pairingAddress, '--pairing-code', pairingCode];
  if (connectAddress) {
    args.push('--connect-address', connectAddress);
  }

  const stringResult = await MenuBarModule.runCli('pair-android-device', args, onStatusUpdate);

  return JSON.parse(stringResult) as PairAndroidDeviceResult;
};

/** Substring the CLI logs once pairing succeeds, before the connect step. */
export const DEVICE_PAIRED_LOG = '[orbit] device paired';

type PairAndroidDeviceWithQRCodeAsyncOptions = {
  serviceName: string;
  pairingCode: string;
};

/**
 * Waits for a device to scan the QR code generated by the app and then pairs
 * with it. Resolves once the device is paired (or the CLI times out waiting).
 */
export const pairAndroidDeviceWithQRCodeAsync = async (
  { serviceName, pairingCode }: PairAndroidDeviceWithQRCodeAsyncOptions,
  onStatusUpdate?: (status: string) => void
) => {
  const args = ['--service-name', serviceName, '--pairing-code', pairingCode];

  const stringResult = await MenuBarModule.runCli('pair-android-device-qr', args, onStatusUpdate);

  return JSON.parse(stringResult) as PairAndroidDeviceResult;
};

export type AndroidPairingService = { name: string; address: string };

/**
 * List Android devices currently in Wi-Fi pairing mode (discovered over mDNS),
 * so the user can pick one to pair with instead of typing its address.
 */
export const listAndroidPairingServicesAsync = async (): Promise<AndroidPairingService[]> => {
  const stringResult = await MenuBarModule.runCli('list-android-pairing-services', [], undefined);

  return JSON.parse(stringResult) as AndroidPairingService[];
};
