require 'pathname'

rn_macos_path = File.dirname(`node --print "require.resolve('react-native-macos/package.json')"`)
require File.join(rn_macos_path, "scripts/react_native_pods")
require File.join(File.dirname(`node --print "require.resolve('@react-native-community/cli-platform-ios/package.json')"`), "native_modules")

base_path = Dir.pwd
# use_react_native does not support relative absolute paths
relative_rn_macos_path = Pathname.new(rn_macos_path).relative_path_from(Pathname.new(base_path)).to_s

target 'ExpoMenuBar-macOS' do
  platform :macos, '10.15'
  use_native_modules!
  use_react_native!(
    :path => relative_rn_macos_path,
    # to enable hermes on macOS, change `false` to `true` and then install pods
    :hermes_enabled => true
  )

  # Pods specifically for macOS target
end

target 'ExpoMenuBar-iOS' do
  platform :ios, '12.4'
  use_native_modules!
  use_react_native!(:path => relative_rn_macos_path)

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable these next few lines.
  use_flipper!

  post_install do |installer|
    react_native_post_install(installer, relative_rn_macos_path)
    __apply_Xcode_12_5_M1_post_install_workaround(installer)
  end
  # Pods specifically for iOS target
end
